cws_site/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from home import views
urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^members/', include('members.urls', namespace='members')),
    url(r'^leaderboard/', include('leaderboard.urls', namespace='leaderboard')),
    url(r'^user/', include('user_profile.urls', namespace='user')),
    url(r'^events/', include('events.urls', namespace='events')),
    url(r'^console/', include('console.urls', namespace='console')),
    url(r'^admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

events/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
app_name="events"
from . import views
urlpatterns = [
    path('editorials/<str:name>',views.view_editorial,name="view_editorial"),
    path('add_editorial/<str:problem_name>',views.add_editorial,name="add_editorial"),
    path('like_editorial/<str:editorial_name>',views.like_editorial,name="like_editorial"),
    path('sessions',views.view_sessions, name="view_sessions"),
    path('problems',views.view_problems, name="view_problems"),
    path('problems/<str:problem_name>',views.view_problem, name="view_problem"),
    path('sessions/<str:session_name>',views.view_session, name="view_session"),
    path('', views.view_events, name="view_events"),
    path('<str:event_name>',views.view_event, name="view_event"),
]

user_profile/urls.py
from django.conf.urls import url

from . import views

app_name = "user"

urlpatterns = [
    url(r'^$', views.profile, name="profile"),
    url(r'^register/$', views.register, name="register"),
    url(r'^coding_accounts/$',views.coding_accounts, name="coding_accounts"),
    url(r'^login/$', views.login_user, name="login"),
    url(r'^logout/$', views.logout_user, name="logout"),
    url(r'^user_info/$', views.user_infos, name="user_infos")   
]

user_profile/forms.py
from collections import OrderedDict

from django import forms
from django.contrib.auth.models import User

from user_profile.models import UserProfile
from user_profile.models import Site_user

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['display_name', 'display_pic', 'reg_number','bio']
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['display_pic'].label = "URL to the photo -> http://giphy.com/"
        self.fields['display_pic'].widget.attrs.update({
            'class': 'form-control validate',
        })

        self.fields['display_name'].label = 'Display Name'
        self.fields['display_name'].widget.attrs.update({
            'class': 'form-control validate',
        })
        self.fields['display_name'].required=True

        self.fields['reg_number'].label = 'NITC Registration Number-in CAPITALS'
        self.fields['reg_number'].widget.attrs.update({
            'class': 'form-control validate',
        })
        self.fields['reg_number'].required = True

        self.fields['bio'].label = 'Short Description/Tag Line'
        self.fields['bio'].widget.attrs.update({
            'class': 'form-control validate',
        })


class UserForm(forms.ModelForm):
    password_validation = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        #remove redundancy by declaring things here rather refer them to model.
        #https://docs.djangoproject.com/en/2.1/topics/forms/modelforms/
        #Model Forms have another kwarg, instance, that holds the instance we’re editing.
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        #https://stackoverflow.com/questions/19197684/clarification-when-where-to-use-super-in-django-python
        #why super- super gives parent objects
        self.fields['username'].label = 'Username (Format: firstname_lastname)'
        self.fields['username'].widget.attrs.update({
            'class': 'form-control validate',
        })

        self.fields['email'].label = 'User email'
        self.fields['email'].widget = forms.EmailInput()
        self.fields['email'].widget.attrs.update({
            'class': 'form-control validate',
        })

        self.fields['password'].label = 'Password'
        self.fields['password'].widget = forms.PasswordInput()
        self.fields['password'].widget.attrs.update({
            'class': 'form-control validate',
        })

        self.fields['password_validation'].label = 'Password verification'
        self.fields['password_validation'].widget = forms.PasswordInput()
        self.fields['password_validation'].widget.attrs.update({
            'class': 'form-control validate',
        })
        #if the password has already been set or user registered already.
        if self.instance.pk is not None:
            self.fields['password_validation'].required = False
            self.fields['password_validation'].label = 'New password verification'
            self.fields['password'].required = False
            self.fields['password'].label = 'New password'

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email:
            raise forms.ValidationError('An email is required')
        elif (self.instance and User.objects.filter(email=email).exclude(id=self.instance.id).count() != 0) or \
                (not self.instance and User.objects.filter(email=email).count() != 0):
            raise forms.ValidationError('An account using this email already exists.')
        return email

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        password_validation = cleaned_data.get("password_validation")
        if password or password_validation:
            if password_validation != password:
                error = "Passwords don't match."
                raise forms.ValidationError(error)
        return cleaned_data


class LoginForm(forms.Form):
    username_or_email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        self.fields['username_or_email'].label = 'Username or email'
        self.fields['username_or_email'].widget.attrs.update({
            'class': 'form-control validate',
        })

        self.fields['password'].label = 'Password'
        self.fields['password'].widget.attrs.update({
            'class': 'form-control validate'
        })


class CodingAccountForm(forms.ModelForm):
    class Meta:
        model = Site_user
        fields = ['username_on_site','sites','url']
    def __init__(self, *args, **kwargs):
        super(CodingAccountForm, self).__init__(*args, **kwargs)
        self.fields['username_on_site'].label = 'Username on platform'
        self.fields['username_on_site'].widget.attrs.update({
            'class': 'form-control validate',
        })
        self.fields['url'].label = 'url'
        self.fields['url'].widget.attrs.update({
            'class': 'form-control validate',
        })

        self.fields['sites'].label = 'Platform'
        self.fields['sites'].widget.attrs.update({
            'class': 'form-control validate',
        })

user_profile/views.py
import logging

from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpRequest
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt
from cws_site import settings

from user_profile.forms import UserForm, UserProfileForm, LoginForm,CodingAccountForm
from user_profile.models import Site_user,Site
from events.models import PerSessionUserLikes,Session
#logger = logging.getLogger(__name__)


def create_or_update_user(request: HttpRequest, user_form: UserForm, user_profile_form: UserProfileForm, creating: bool) -> HttpResponse:
    if not user_form.is_valid() or not user_profile_form.is_valid():
        messages.add_message(request, messages.ERROR, user_form.non_field_errors())
    else:
        try:
            if creating:
                user = User.objects.create_user(username=user_form.cleaned_data['username'],
                                                email=user_form.cleaned_data['email'],
                                                password=user_form.cleaned_data['password'],
                                                is_active=True)
            else:
                user = user_form.instance
                user.username = user_form.cleaned_data['username']
                new_pass = user_form.cleaned_data.get('password')
                if new_pass:
                    user.set_password(new_pass)
                else:
                    user.password = user_form.initial['password']
                user.email = user_form.cleaned_data['email']
                user.save()
            user_profile = user_profile_form.save(commit=False)
            user_profile.user_info = user
            user_profile.save()
            if creating:
                sessionlist = Session.objects.all()
                for item in sessionlist:
                    persessionuserlikes = PerSessionUserLikes(user=user_profile,session=item)
                    persessionuserlikes.save()
                messages.add_message(request, messages.SUCCESS, 'Congratulations ! Your user is created.')
                t = authenticate(username=user.username, password=user_form.cleaned_data['password'])
                if t is not None:
                    login(request, t)
            else:
                messages.add_message(request, messages.SUCCESS, 'Your user has been updated.')
            return redirect(reverse('user:profile'))
        except Exception:
            #logger.exception('Error while creating/updating a user. creating=' + str(creating) + ', req=' + "\n".join(request.readlines()))
            messages.add_message(request, messages.ERROR, 'Error, Contact Admin')
    return None


@require_http_methods(["POST"])
@never_cache
@csrf_exempt
def logout_user(request: HttpRequest) -> HttpResponse:
    if request.user.is_authenticated:
        logout(request)
        messages.add_message(request, messages.INFO, "You've been logged out. Have a nice day.")
    else:
        messages.add_message(request, messages.ERROR, "Mmmh.. You have to be logged in to do this.")
    return redirect(reverse('user:login'))


@sensitive_post_parameters()
@csrf_protect
@never_cache
@require_http_methods(["GET", "POST"])
def register(request: HttpRequest) -> HttpResponse:
    if settings.REGISTER_ENABLED:
        if request.method == "POST":
            user_profile_form = UserProfileForm(request.POST, request.FILES)
            user_form = UserForm(request.POST)
            response = create_or_update_user(request, user_form, user_profile_form, True)
            if response is not None:
                return response
        else:
            user_profile_form = UserProfileForm()
            user_form = UserForm()
    else:
        messages.add_message(request, messages.ERROR, "You cannot register anymore, please contact an admin.")
    return render(request, 'user_profile/register.html', locals())


@sensitive_post_parameters()
@csrf_protect
@never_cache
@require_http_methods(["GET", "POST"])
def login_user(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user_name_or_email = login_form.cleaned_data['username_or_email']
            password = login_form.cleaned_data['password']
            user = authenticate(username=user_name_or_email, password=password)
            if user is None:
                user_by_mail = User.objects.filter(email=user_name_or_email)
                if user_by_mail and user_by_mail[0]:
                    username = user_by_mail[0].username
                    user = authenticate(username=username, password=password)
            if user is None:
                messages.add_message(request, messages.ERROR, 'Wrong user name or password. Please try again.')
            else:
                login(request, user)
                messages.add_message(request, messages.SUCCESS, "You've been successfully logged in.")
                return redirect(request.GET.get('next', reverse('home')))
    else:
        login_form = LoginForm()
    return render(request, 'user_profile/login.html', locals())

@never_cache
@require_http_methods(["GET"])
def user_infos(request):
    resp = {
        "is_logged_in": request.user.is_authenticated,
        "is_admin": request.user.is_staff,
    }
    if request.user.is_authenticated:
        resp["pk"] = request.user.pk
    return JsonResponse(resp)


@login_required
@csrf_protect
@never_cache
@require_http_methods(["GET", "POST"])
def profile(request: HttpRequest) -> HttpResponse:
    user = request.user
    if not hasattr(user, 'userprofile'):
        messages.add_message(request, messages.ERROR, 'We tried really hard to find it but this user does not exists.')
        return redirect(reverse('user:login'))
    user_profile = user.userprofile

    if request.method == "POST":
        user_form = UserForm(request.POST, instance=user)
        user_profile_form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        response = create_or_update_user(request, user_form, user_profile_form, False)
        if response is not None:
            return response
    else:
        user_form = UserForm(instance=user)
        user_profile_form = UserProfileForm(instance=user_profile)

    return render(request, 'user_profile/profile.html', locals())


def update_user_coding_account(request: HttpRequest, coding_account_form: CodingAccountForm) -> HttpResponse:
    if not coding_account_form.is_valid():
        messages.add_message(request, messages.ERROR, coding_account_form.non_field_errors())
    else:
        try:
            
            user=request.user
            user_infos=user.userprofile
            site=Site_user(username_on_site=coding_account_form.cleaned_data['username_on_site'],
                           url=coding_account_form.cleaned_data['url'],
                           sites=Site.objects.get(sitename=coding_account_form.cleaned_data['sites']),
                           user_info=user_infos
                            )
            
            site.save()
            messages.add_message(request, messages.SUCCESS, 'Created Successfully.')
            return redirect(reverse('user:coding_accounts'))
        except Exception:
            #logger.exception('Error while creating/updating a user. creating=' + str(creating) + ', req=' + "\n".join(request.readlines()))
            messages.add_message(request, messages.ERROR, 'Sorry, an error occurred, please alert an admin.')
    return None

@login_required
@csrf_protect
@never_cache
@require_http_methods(["GET", "POST"])
def coding_accounts(request: HttpRequest) -> HttpResponse:
    user = request.user
    if not hasattr(user, 'userprofile'):
        messages.add_message(request, messages.ERROR, 'We tried really hard to find it but this user does not exists.')
        return redirect(reverse('user:login'))
    user_profile = user.userprofile
    queryforsites=Site_user.objects.filter(user_info=user_profile)
    if request.method == "POST":
        coding_account_form=CodingAccountForm(request.POST)
        queryforsites=Site_user.objects.filter(user_info=user_profile)
        response=update_user_coding_account(request, coding_account_form)
        if response is not None:
            return response
    else:
        coding_account_form=CodingAccountForm()
    return render(request, 'user_profile/add_coding_account.html', locals())

user_profile/templates/user_profile/add_coding_account.html
{% extends "layout.html" %}
{% load staticfiles %}

{% block login_active %}active{% endblock %}
{% block title %}{{ block.super }} | Coding Accounts{% endblock %}

{% block body %}
    <div class="row">
    <div class="col">
         <div class="table-responsive">
                            <table class="table">
                                <thead><td>Username</td><td>Sitename</td><td>URL</td></thead>
                                {% for item in queryforsites %}
                                    <tr><td>{{item.username_on_site}}</td><td>{{item.sites.sitename}}</td><td>{{item.url}}</td> </tr>
                                {% endfor %}

                            </table>
         </div>
    </div>
        <div class="col">
                <div class="card card-block">
                    <form method="post" action="" id="form-login">
                        <fieldset>

                            {% for field in coding_account_form %}
                                <div class="md-form {% if field.errors %}has-error{% endif %}">
                                    {{ field }}
                                    <label for="id_{{ field.name }}">{{ field.label }}</label>
                                    {% for error in field.errors %}
                                        <p class="text-danger">{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endfor %}
    
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="col-md-10 col-md-offset-2">
                                    <button type="submit" class="btn btn-default">Add</button>
                                </div>
                            </div>
    
                        </fieldset>
                    </form>
                </div>
            </div>
    </div>

{% endblock %}

user_profile/templates/user_profile/login.html
{% extends "layout.html" %}
{% load staticfiles %}

{% block login_active %}active{% endblock %}
{% block title %}{{ block.super }} | Login{% endblock %}

{% block body %}
    <div class="row">
        <div class="col">
            <div class="jumbotron">
                <h1>Log in to Coding With Seniors</h1>
                <p>New around here ? You can also <a href="{% url 'user:register' %}">register here</a>.</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="card card-block">
                <form method="post" action="" id="form-login">
                    <fieldset>
                        {% for field in login_form %}
                            <div class="md-form {% if field.errors %}has-error{% endif %}">
                                {{ field }}
                                <label for="id_{{ field.name }}">{{ field.label }}</label>
                                {% for error in field.errors %}
                                    <p class="text-danger">{{ error }}</p>
                                {% endfor %}
                            </div>
                        {% endfor %}

                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-2">
                                <button type="submit" class="btn btn-default">Login</button>
                            </div>
                        </div>

                    </fieldset>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

user_profile/templates/user_profile/profile.html
{% extends "layout.html" %}
{% load staticfiles %}

{% block profile_active %}active{% endblock %}
{% block account_active %}active{% endblock %}
{% block title %}{{ block.super }} | Profile{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row vertical-centered" id="team-header">
            {% if user_profile.display_pic %}
                <div class="col-lg-3 hidden-lg-down">
                    <img src="{{ user_profile.display_pic}}" alt="&nbsp;" class="abs-center img-fluid profile-gif"
                         id="team-logo" height="150px" width="150px" >
                </div>
            {% endif %}
        </div>

        <div class="row" style="margin-top: 20px">
            <div class="col">
                <div class="card card-block">
                    <h2>Update your information below.</h2>
                    <form method="post" action="" enctype="multipart/form-data" class="form-horizontal"
                          id="form-update-profile">
                        <fieldset>
                            {% for field in user_form %}
                                <div class="md-form {% if field.errors %}has-error{% endif %}">
                                    {{ field }}
                                    <label for="id_{{ field.name }}">{{ field.label }}</label>
                                    {% for error in field.errors %}
                                        <p class="text-danger">{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endfor %}

                            {% for field in user_profile_form %}
                                {% if field == 'FileInput' %}
                                    <div class="md-group col {% if field.errors %}has-error{% endif %} file">
                                        <label for="id_{{ field.name }}">{{ field.label }}</label>
                                        {{ field }}
                                        {% for error in field.errors %}
                                            <p class="text-danger">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    <div class="md-form {% if field.errors %}has-error{% endif %}">
                                        {{ field }}
                                        <label for="id_{{ field.name }}">{{ field.label }}</label>
                                        {% for error in field.errors %}
                                            <p class="text-danger">{{ error }}</p>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            {% endfor %}

                            {% csrf_token %}
                            <div class="form-group">
                                <div class="col">
                                    <button type="submit" class="btn btn-default">Update</button>
                                </div>
                            </div>

                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
        <div class="row" style="margin-top: 20px">
            <div class="col">
                <a href="/user/coding_accounts/"><button class="btn btn-default">Add Coding Accounts</button></a>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script type="text/javascript">
        $(document).ready(function () {
            var pass = $("#id_password");
            var pass_confirm = $("#id_password_validation");
            pass.on("input", function () {
                if (pass.val().length) {
                    pass_confirm.attr('required', true);
                }
                else {
                    pass_confirm.attr('required', false);
                }
            });
            pass_confirm.on("input", function () {
                if (pass_confirm.val().length) {
                    pass.attr('required', true);
                }
                else {
                    pass.attr('required', false);
                }
            })
        });

    </script>
{% endblock %}

user_profile/templates/user_profile/register.html
{% extends "layout.html" %}
{% load staticfiles %}


{% block register_active %}active{% endblock %}
{% block title %}{{ block.super }} | Register{% endblock %}

{% block body %}
    <div class="row">
        <div class="col">
            <div class="jumbotron">
                <h1>Register to Coding With Seniors</h1>
                <p>
                    To register please fill in the form below.
                    If you already have an account you can <a href="{% url 'user:login' %}">log in here</a>.
                </p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="card card-block">
                <form method="post" action="" enctype="multipart/form-data" id="form-register">
                    <fieldset>
                        {% for field in user_form %}
                            <div class="md-form {% if field.errors %}has-error{% endif %}">
                                {{ field }}
                                <label for="id_{{ field.name }}">{{ field.label }}</label>
                                {% for error in field.errors %}
                                    <p class="text-danger">{{ error }}</p>
                                {% endfor %}
                            </div>
                        {% endfor %}

                        {% for field in user_profile_form %}
                            {% if field == 'FileInput' %}
                                <div class="md-group col {% if field.errors %}has-error{% endif %} file">
                                    <label for="id_{{ field.name }}">{{ field.label }}</label>
                                    {{ field }}
                                    {% for error in field.errors %}
                                        <p class="text-danger">{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% else %}
                                <div class="md-form {% if field.errors %}has-error{% endif %}">
                                    {{ field }}
                                    <label for="id_{{ field.name }}">{{ field.label }}</label>
                                    {% for error in field.errors %}
                                        <p class="text-danger">{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        {% endfor %}

                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col">
                                <button type="submit" class="btn btn-default">Register</button>
                            </div>
                        </div>

                    </fieldset>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script type="text/javascript">
        $(document).ready(function () {
            var pass = $("#id_password");
            var pass_confirm = $("#id_password_validation");
            pass.on("input", function () {
                if (pass.val().length) {
                    pass_confirm.attr('required', true);
                }
                else {
                    pass_confirm.attr('required', false);
                }
            });
            pass_confirm.on("input", function () {
                if (pass_confirm.val().length) {
                    pass.attr('required', true);
                }
                else {
                    pass.attr('required', false);
                }
            })
        });

    </script>
{% endblock %}