cws_site/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from home import views
urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^members/', include('members.urls', namespace='members')),
    url(r'^leaderboard/', include('leaderboard.urls', namespace='leaderboard')),
    url(r'^user/', include('user_profile.urls', namespace='user')),
    url(r'^events/', include('events.urls', namespace='events')),
    url(r'^console/', include('console.urls', namespace='console')),
    url(r'^admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

events/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
app_name="events"
from . import views
urlpatterns = [
    path('editorials/<str:name>',views.view_editorial,name="view_editorial"),
    path('add_editorial/<str:problem_name>',views.add_editorial,name="add_editorial"),
    path('like_editorial/<str:editorial_name>',views.like_editorial,name="like_editorial"),
    path('sessions',views.view_sessions, name="view_sessions"),
    path('problems',views.view_problems, name="view_problems"),
    path('problems/<str:problem_name>',views.view_problem, name="view_problem"),
    path('sessions/<str:session_name>',views.view_session, name="view_session"),
    path('', views.view_events, name="view_events"),
    path('<str:event_name>',views.view_event, name="view_event"),
]

user_profile/urls.py
from django.conf.urls import url

from . import views

app_name = "user"

urlpatterns = [
    url(r'^$', views.profile, name="profile"),
    url(r'^register/$', views.register, name="register"),
    url(r'^coding_accounts/$',views.coding_accounts, name="coding_accounts"),
    url(r'^login/$', views.login_user, name="login"),
    url(r'^logout/$', views.logout_user, name="logout"),
    url(r'^user_info/$', views.user_infos, name="user_infos")   
]

cws_site/templates/layout.html
<!DOCTYPE html>
<html lang="en" style="height: 100%;">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Coding with seniors is a Competitive coding tutorial session organised by CSEA NIT Calicut.">
    <meta name="keywords" content="CSEA,NITC,CWS">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>
        {% block title %}Coding with Seniors{% endblock %}
    </title>

    <!-- CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" 
                integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.3.0/css/mdb.min.css">#}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />

    <!-- Font Awesome -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'cws_site/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'cws_site/css/jquery-ui.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    {% block css %}{% endblock %}
    <!-- /CSS -->

</head>
<body style="min-height: 100%;display: flex;flex-direction: column;">

<nav class="navbar navbar-expand-sm navbar-dark bg-primary" >
    <div class="container">
        <a class="navbar-brand" href="/" style="margin-top: 2px; margin-right: 30px;">Coding With Seniors</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
       
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul id="main-menu" class="navbar-nav mr-auto">
                <li class="nav-item {% block home_active %}{% endblock %}"><a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Sessions
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="/events">Events</a>
                      <a class="dropdown-item" href="/events/sessions">Sessions</a>
                      <a class="dropdown-item" href="/events/problems">Problems</a>
                    </div>
                </li>
                <li class="nav-item"><a class="nav-link" href="/members">Members</a></li>
                <li class="nav-item"><a class="nav-link" href="/leaderboard">Leaderboard</a></li>

            </ul>
            <ul id="account-menu" class="navbar-nav">
            </ul>
        </div>
    </div>
    <form id="logout-form" method="POST" action="{% url 'user:logout' %}">
    </form>
</nav>

<section class="{% block container %}container{% endblock %}" style="margin-top: 15px;flex: 1;">
    {% block body %}
    {% endblock %}
</section>

<footer id="myFooter">
        <div class="container">
            <ul>
                <li><a href="http://assoc.cse.nitc.ac.in/" target="_blank">CSEA NITC</a></li>
                <li><a href="http://assoc.cse.nitc.ac.in/contact.php" target="_blank">Contact us</a></li>
            </ul>
        <p class="footer-copyright">© 2018 Copyright</p>
        </div>
        <div class="footer-social">
            <a href="https://www.facebook.com/CSEA.NITC/" class="social-icons" target="_blank"><i class="fa fa-facebook"></i></a>
            <a href="https://www.linkedin.com/in/karthik-ammanamanchi/" class="social-icons" target="_blank"><i class="fa fa-linkedin"></i></a>
            <a href="https://twitter.com/cseanitc" class="social-icons" target="_blank"><i class="fa fa-twitter"></i></a>
        </div>
    </footer>

<!-- Javascript -->
<script
			  src="https://code.jquery.com/jquery-3.3.1.min.js"
			  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
			  crossorigin="anonymous"></script>

<script
			  src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
			  integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
			  crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

{% block messages %}
    {% if messages %}
        <script>
            toastr.options.closeDuration = 5000;
            {% for msg in messages %}
                toastr.{{ msg.level_tag }}('{{ msg.message }}');
            {% endfor %}
        </script>
    {% endif %}
{% endblock %}
<script>
    $(document).ready(function () {
        $('.dropdown-toggle').dropdown();
    });
</script>
<script type="text/javascript">

    if (location.protocol != 'https:') {
        // location.href = 'https:' + window.location.href.substring(window.location.protocol.length);
    }
    $(document).ready(function () {
        $.ajax({
            type: "GET",
            url: "{% url 'user:user_infos' %}",
            success: function (data) {
                var accountMenu = $("#account-menu");
                if(data.is_admin) {
                    accountMenu.append('<li id="console" class="nav-item "><a class="nav-link" href=" /console" >Console</a></li>');
                }
                if (data.is_logged_in) {
                    accountMenu.append('<li id="profile" class="nav-item {% block profile_active %}{% endblock %}"><a class="nav-link" href="{% url 'user:profile' %}">Profile</a></li>');
                    accountMenu.append('<li id="logout" class="nav-item"><a class="nav-link" onclick=$("form#logout-form").submit()>Log out</a></li>');

                    {% block additional_user_actions %}{% endblock %}
                } else {
                    accountMenu.append('<li id="register" class="nav-item {% block register_active %}{% endblock %}"><a class="nav-link" href="{% url 'user:register' %}">Register</a></li>');
                    accountMenu.append('<li id="login" class="nav-item {% block login_active %}{% endblock %}"><a class="nav-link" href="{% url 'user:login' %}">Log in</a></li>');
                }


            },
            error: function (data) {
                console.log(data);
            }
        });
    });
</script>

{% block javascript %}{% endblock %}
<!-- /Javascript -->
</body>

</html>